export interface MediaItem {
  type: 'image' | 'video';
  src: string;
  alt: string;
}

export const mediaItems: MediaItem[] = [
  { type: 'image', src: '/gallery/pics/img1.jpg', alt: 'Character Design 1' },
  { type: 'image', src: '/gallery/pics/img2.jpg', alt: 'Character Design 2' },
  { type: 'image', src: '/gallery/pics/img3.jpg', alt: 'Background Art 1' },
  { type: 'image', src: '/gallery/pics/img4.jpg', alt: 'Background Art 2' },
  { type: 'image', src: '/gallery/pics/img5.jpg', alt: 'Concept Art 1' },
  { type: 'image', src: '/gallery/pics/img6.jpg', alt: 'Concept Art 2' },
  { type: 'image', src: '/gallery/pics/img7.jpg', alt: 'Prop Design 1' },
  { type: 'image', src: '/gallery/pics/img8.jpg', alt: 'Prop Design 2' },
  { type: 'image', src: '/gallery/pics/img9.jpg', alt: 'Storyboard Sketch 1' },
  { type: 'image', src: '/gallery/pics/img10.jpg', alt: 'Storyboard Sketch 2' },
  { type: 'image', src: '/gallery/pics/img11.jpg', alt: 'Character Pose 1' },
  { type: 'image', src: '/gallery/pics/img12.jpg', alt: 'Character Pose 2' },
  { type: 'image', src: '/gallery/pics/img13.jpg', alt: 'Scene Illustration 1' },
  { type: 'image', src: '/gallery/pics/img14.jpg', alt: 'Scene Illustration 2' },
  { type: 'image', src: '/gallery/pics/img15.jpg', alt: 'Color Study 1' },
  { type: 'image', src: '/gallery/pics/img16.jpg', alt: 'Color Study 2' },
  { type: 'image', src: '/gallery/pics/img17.jpg', alt: 'Manga Panel 1' },
  { type: 'image', src: '/gallery/pics/img18.jpg', alt: 'Manga Panel 2' },
  { type: 'image', src: '/gallery/pics/img19.jpg', alt: 'Illustration 1' },
  { type: 'image', src: '/gallery/pics/img20.jpg', alt: 'Illustration 2' },
  { type: 'image', src: '/gallery/pics/img21.jpg', alt: 'Illustration 3' },
  { type: 'image', src: '/gallery/pics/img22.jpg', alt: 'Illustration 4' },
  { type: 'image', src: '/gallery/pics/img23.jpg', alt: 'Illustration 5' },
  { type: 'image', src: '/gallery/pics/img24.jpg', alt: 'Illustration 6' },
  { type: 'image', src: '/gallery/pics/img25.jpg', alt: 'Illustration 7' },
  { type: 'image', src: '/gallery/pics/img26.jpg', alt: 'Illustration 8' },
  { type: 'image', src: '/gallery/pics/img27.jpg', alt: 'Illustration 9' },
  { type: 'image', src: '/gallery/pics/img28.jpg', alt: 'Illustration 10' },
  { type: 'image', src: '/gallery/pics/img29.jpg', alt: 'Illustration 11' },
  { type: 'image', src: '/gallery/pics/img30.jpg', alt: 'Illustration 12' },
  { type: 'image', src: '/gallery/pics/img31.jpg', alt: 'Illustration 13' },
  { type: 'image', src: '/gallery/pics/img32.jpg', alt: 'Illustration 14' },
  { type: 'image', src: '/gallery/pics/img33.jpg', alt: 'Illustration 15' },
  { type: 'image', src: '/gallery/pics/img34.jpg', alt: 'Illustration 16' },
  { type: 'image', src: '/gallery/pics/img35.jpg', alt: 'Illustration 17' },
  { type: 'image', src: '/gallery/pics/img36.jpg', alt: 'Illustration 18' },
  { type: 'image', src: '/gallery/pics/img37.jpg', alt: 'Illustration 19' },
  { type: 'image', src: '/gallery/pics/img38.jpg', alt: 'Illustration 20' },
  { type: 'image', src: '/gallery/pics/img39.jpg', alt: 'Illustration 21' },
  { type: 'image', src: '/gallery/pics/img40.jpg', alt: 'Illustration 22' },
  { type: 'image', src: '/gallery/pics/img41.jpg', alt: 'Illustration 23' },
  { type: 'image', src: '/gallery/pics/img42.jpg', alt: 'Illustration 24' },
  { type: 'image', src: '/gallery/pics/img43.jpg', alt: 'Illustration 25' },
  { type: 'image', src: '/gallery/pics/img44.jpg', alt: 'Illustration 26' },
  { type: 'image', src: '/gallery/pics/img45.jpg', alt: 'Illustration 27' },
  { type: 'image', src: '/gallery/pics/img46.jpg', alt: 'Illustration 28' },
  { type: 'image', src: '/gallery/pics/img47.jpg', alt: 'Illustration 29' },
  { type: 'image', src: '/gallery/pics/img48.jpg', alt: 'Illustration 30' },
  { type: 'image', src: '/gallery/pics/img49.jpg', alt: 'Illustration 31' },
  { type: 'image', src: '/gallery/pics/img50.jpg', alt: 'Illustration 32' },
  { type: 'image', src: '/gallery/pics/img51.jpg', alt: 'Illustration 33' },
  { type: 'image', src: '/gallery/pics/img52.jpg', alt: 'Illustration 34' },
  { type: 'image', src: '/gallery/pics/img53.jpg', alt: 'Illustration 35' },
  { type: 'image', src: '/gallery/pics/img54.jpg', alt: 'Illustration 35' },
  { type: 'image', src: '/gallery/pics/img55.jpg', alt: 'Illustration 35' },
  { type: 'video', src: '/gallery/videos/video1.mp4', alt: 'Animation Clip 2' },
  { type: 'video', src: '/gallery/videos/video2.mp4', alt: 'Animation Clip 2' },
  { type: 'video', src: '/gallery/videos/video3.mp4', alt: 'Animation Clip 3' },
  { type: 'video', src: '/gallery/videos/video4.mp4', alt: 'Animation Clip 4' },
  { type: 'video', src: '/gallery/videos/video5.mp4', alt: 'Animation Clip 5' },
  { type: 'video', src: '/gallery/videos/video6.mp4', alt: 'Animation Clip 6' },
  { type: 'video', src: '/gallery/videos/video7.mp4', alt: 'Animation Clip 7' },
  { type: 'video', src: '/gallery/videos/video8.mp4', alt: 'Animation Clip 8' },
  { type: 'video', src: '/gallery/videos/video9.mp4', alt: 'Animation Clip 9' },  
  { type: 'video', src: '/gallery/videos/video10.mp4', alt: 'Animation Clip 10' },
  { type: 'video', src: '/gallery/videos/video11.mp4', alt: 'Animation Clip 11' },
  { type: 'video', src: '/gallery/videos/video12.mp4', alt: 'Animation Clip 12' },
  { type: 'video', src: '/gallery/videos/video13.mp4', alt: 'Animation Clip 13' },
  { type: 'video', src: '/gallery/videos/video14.mp4', alt: 'Animation Clip 14' },
  { type: 'video', src: '/gallery/videos/video15.mp4', alt: 'Animation Clip 15' },
  { type: 'video', src: '/gallery/videos/video16.mp4', alt: 'Animation Clip 16' },
  { type: 'video', src: '/gallery/videos/video17.mp4', alt: 'Animation Clip 17' },
];